### ISSUE TITLE
Export function in webpack configuration

### ISSUE THREAD

**Issue by toverux** [meltedspark/angular-builders#135]
Migrating an Angular project with full custom webpack configuration, I'd like to use a function in my webpack configuration. When a function is passed, Webpack executes it and passes an "env" object and the argv: https://webpack.js.org/configuration/configuration-types/#exporting-a-function

I tried this:

```js
module.exports = function (env) {
    throw env;
};
```

But nothing happens, meaning that angular-builders doesn't execute it (exporting an object works, as expected).

My final goal however, was to see if I can get some info from Angular about the build, like : is the build in production mode?

I'd like to know what environment Angular uses so I can inherit from it and apply different plugins or loaders based on the environment we're in, like in the past.

Do you see a way to achieve that?

In the worst case scenario, I can use NODE_ENV and the --prod switch, but that won't match the setting Angular uses (or will it?).

**Comment by meltedspark** [comment]
That is an interesting question.
Let's split it into two different features:
1. Support webpack config provided with a function rather than an object. This really shouldn't be a problem, it should be supported and it will be. 
2. Provide an access to Angular CLI execution environment within a webpack configuration. This one is not straight forward, because the webpack configuration you provide is simply merged with a webpack configuration provided by Angular (which is already configured according to the environment). Maybe the Angular environment config is already present in `process.env` (in this case it wouldn't be a problem to access it from within the webpack config) but maybe it is not. In this case it should be somehow passed in.  
I'll investigate this one and will see what can be done here.

**Comment by toverux** [comment]
Thank you!
For now I simply use NODE_ENV to pilot my webpack script, en take care that --prod is set accordingly.
Meaning that I have a npm script that looks like `cross-env NODE_ENV=production ng build --prod`.
Before that, my build script was capable of doing static builds in dev or prod more, whereas now it has to be hardcoded in the command line.
So I can live without it if that's not possible, but sure that would be nice to have.
