### ISSUE TITLE
Example of replacing the minimizer

### ISSUE THREAD

**Issue by RyanHow** [meltedspark/angular-builders#144]
**Is your feature request related to a problem? Please describe.**
I'm trying to replace the options for the minimizer in angular-cli 7. But it doesn't seem to be working. No matter what config I set, the standard minimizer seems to be running.

**Describe the solution you'd like**
Is there a way to view the final webpack config output? I'm concerned I'm just appending another minimizer rather than replacing it. Or just an example of replacing the minimizer. I'm not 100% clear on how the "merging" of configs works.

Thanks!

This is my extra-webpack.config.js

```
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
    optimization: {
        minimizer: [new TerserPlugin({
            parallel: true,
            cache: true,
            terserOptions: {
                ecma: undefined,
                warnings: false,
                parse: {},
                compress: {
                    warnings: false, // Suppress uglification warnings
                    pure_getters: true,
                    unsafe: true,
                    unsafe_comps: true
                },
                mangle: true, // Note `mangle.properties` is `false` by default.
                module: false,
                output: null,
                toplevel: false,
                nameCache: null,
                ie8: false,
                keep_classnames: undefined,
                keep_fnames: false,
                safari10: false
            }
        })]
    }
};
```

**Comment by meltedspark** [comment]
Have you specified merge strategy `replace` for `optimization`? You might want to take a look at [this](https://dev.to/meltedspark/comment/5mcg) comment.  
Regarding viewing the final webpack conifg - not possible without changing the sources. I'm considering adding a `debug` or `verbose` option. Would be useful to me as well as to the users.

**Comment by RyanHow** [comment]
Thanks so much!. Worked like a charm. You are a legend.

**Comment by Xambey** [comment]
The merge strategy no longer works, you should use a similar approach:

```
module.exports = (config, options) => {
    config.optimization.minimizer.filter (({constructor: {name}}) => name === 'TerserPlugin')
        .forEach (terser => terser.options.terserOptions.keep_fnames = true);

    return config;
};
```

The default config for Angular 8:
```
[
  HashedModuleIdsPlugin {
    options: {
      context: null,
      hashFunction: 'md4',
      hashDigest: 'base64',
      hashDigestLength: 4
    }
  },
  BundleBudgetPlugin {options: {budgets: [Array]}},
  CleanCssWebpackPlugin {
    _options: {sourceMap: true, test: [Function: test]}
  },
  TerserPlugin {
    options: {
      test: /\.m?js(\?.*)?$/i,
      chunkFilter: [Function: chunkFilter],
      warningsFilter: [Function: warningsFilter],
      extractComments: false,
      sourceMap: true,
      cache: true
      cacheKeys: [Function: cacheKeys],
      parallel: true
      include: undefined,
      exclude: undefined,
      minify: undefined,
      terserOptions: [Object]
    }
  },
  TerserPlugin {
    options: {
      test: /\.m?js(\?.*)?$/i,
      chunkFilter: [Function: chunkFilter],
      warningsFilter: [Function: warningsFilter],
      extractComments: false,
      sourceMap: true,
      cache: true
      cacheKeys: [Function: cacheKeys],
      parallel: true
      include: undefined,
      exclude: undefined,
      minify: undefined,
      terserOptions: [Object]
    }
  }
]
```

[Default config](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L553)

**Comment by Zundrium** [comment]
@Xambey Your current example seems to work, however when I change it to `keep_classnames` it does not retain the class names. Any idea what might be the cause?

**Comment by Xambey** [comment]
@Zundrium during the study of the sources it was found that specifically for Terser plugins, the builder ignores the mangling settings, all you can do is turn it off completely. You can read more [here ](https://angular-builders.slack.com/archives/CHLEH4BEY/p1577355095053700)

**Comment by Zundrium** [comment]
@Xambey Alright, thanks.

**Comment by just-jeb** [comment]
So, for any newcomers a short recap of what's been discussed here and researched in the sources.

In order to change the minimizer settings you have to change the configuration of `TerserPlugin`. Nothing complicated, just the old good `custom-webpack` builder, read the docs.

**HOWEVER**, in order for these changes to be applied **the `differentialLoading` must be switched off**.
To do this you can either:

1. Completely drop the support for `es5` by modifying `browserlist` file (only allow browsers that support `es6`).
2. Compile your code to `es5` instead of `es6`, which will effectively support older versions of browsers but increase bundle size. This can be done by setting the target in `tsconfig.json` to `es5` or not setting it at all (`es5` is the default option for Angular).

***Background:***
*After the webpack build is done Angular [is doing](https://github.com/angular/angular-cli/blob/d585f99a3efbd176d3666c357bff919e16bb0dc2/packages/angular_devkit/build_angular/src/browser/index.ts#L328) its own [post-processing](https://github.com/angular/angular-cli/blob/d585f99a3efbd176d3666c357bff919e16bb0dc2/packages/angular_devkit/build_angular/src/utils/process-bundle.ts#L91) which disregards `TerserPlugin` options and does stuff like [mangling](https://github.com/angular/angular-cli/blob/d585f99a3efbd176d3666c357bff919e16bb0dc2/packages/angular_devkit/build_angular/src/utils/process-bundle.ts#L160) in any case.*

**Comment by insel-maz** [comment]
> The merge strategy no longer works, you should use a similar approach:
> 
> ```
> module.exports = (config, options) => {
>     config.optimization.minimizer.filter (({constructor: {name}}) => name === 'TerserPlugin')
>         .forEach (terser => terser.options.terserOptions.keep_fnames = true);
> 
>     return config;
> };
> ```

As of Angular 12, it should be:
```
module.exports = (config, options) => {
	config.optimization.minimizer.filter(({constructor: {name}}) => name === 'JavaScriptOptimizerPlugin')
		.forEach(plugin => plugin.options.keepNames = true);

	return config;
};
```
