### ISSUE TITLE
Custom loaders not working

### ISSUE THREAD

**Issue by euheny** [meltedspark/angular-builders#151]
extra-webpack.config.js loaded but custom loaders not apply.

```
// extra-webpack.config.js
module.exports = {
  module: {
    rules: [
      {
        test: /\.txt$/,
        use: [
          'raw-loader'
        ]
      },
      {
        test: /\.svg$/,
        use: [
          'raw-loader',
          {
            loader: 'svgo-loader',
            options: svgoOptions
          }
        ]
      }
    ]
  }
}
```

```
// test.ts
import * as icon from './svg/archive-drawer.svg';
```
return in console 
```ERROR in test.ts(2,23): error TS2307: Cannot find module './svg/archive-drawer.svg'.```

Pls help. What im doing wrong?

**Comment by meltedspark** [comment]
If the loaders were not applied you would have been getting another error (no appropriate loader or something).  
I believe your issue is very similar to [this](https://medium.com/@csar.vgarcia/hi-first-of-all-thanks-for-this-contribution-7d3fd4851087) one. Please refer to the thread for the things you have to do.  
And please keep me posted regarding your final solution.  
In short it's all about adding a module declaration for `svg` files so that Typescript compiler would recognize them as modules and then adding the typings file to the included files in `tsconfig`.

**Comment by euheny** [comment]
huh. It funny. But it go from angilar-cli builder :) It have own loader for svg. I resolve my case with loader alias. And thx. Info about module declaration was useful.

**Comment by meltedspark** [comment]
Would you mind sharing your final solution here? Might help others who are stuck with the same issue.

**Comment by ViieeS** [comment]
@euheny Hi! I have exactly the same problem. Please, can you share your solution?
