### ISSUE TITLE
Unable to run test by specifying a filename on the command line on a multi-project workspace

### ISSUE THREAD

**Issue by jon301** [meltedspark/angular-builders#169]
**Describe the bug**
Given Jest documentation, Jest supports running a test from the command line by specifying a filepath

https://jestjs.io/docs/en/cli.html#running-from-the-command-line

```
Run only the tests that were specified with a pattern or filename:

jest my-test #or
jest path/to/my-test.js
```

With angular-builders/jest, we get this error :
```
$ ng test tf-web /Users/jonjon/work/typefaster/tf-web/src/app/features/playground/modules/classic/classic.component.spec.ts

Unknown option: '/Users/jonjon/work/typefaster/tf-web/src/app/features/playground/modules/classic/classic.component.spec.ts'
```
**Builder:**
- Jest Builder v7.1.1

**Libraries**
 - `angular-devkit/build-angular`: ~0.11.0

**Comment by meltedspark** [comment]
[Here](https://github.com/meltedspark/angular-builders/issues/130#issuecomment-435466827) is an explanation of what's happening.  
Your case though is much easier, you can just use [testPathPattern](https://jestjs.io/docs/en/cli.html#testpathpattern-regex) option (instead of just passing the path as is pass it with `--testPathPattern`)

**Comment by jon301** [comment]
I've already tried with `testPathPattern` option, it's not very ideal because I need to escape the whole path to make it RegEx friendly, plus Jest still scrapes all test files to apply the regex and skips or runs the ones that matches. This takes a bit more time.

Thank you for your answer anyway, I understand the explanation and the limitations of the Angular CLI.

**Comment by meltedspark** [comment]
Well, Jest documentation suggests that you have to escape the separator if you're on Windows or use `/` instead of `\`.  
And if you specify the full path like in your example it should pick other files.  
But it's still an issue I can explore the option of adding a separate `fileName` option in the builder that will do the same `jest filePath` does.  
If you'd like to have such an option please open a feature request.
