### ISSUE TITLE
ts-nameof (dsherret/ts-nameof)

### ISSUE THREAD

**Issue by Brandejs** [meltedspark/angular-builders#175]
Hi, I'm trying to add to my project [dsherret/ts-nameof](https://github.com/dsherret/ts-nameof). But without success. I tried [ts-nameof-loader](https://www.npmjs.com/package/ts-nameof-loader), but also without success. When I run ng serve, everything works fine, except that _nameof_ is not transformed.

Can anybody please help me with how to set up that?

**Comment by meltedspark** [comment]
Can you please create a minimal repository with reproduction?  
I can't tell for sure (because I haven't seen your configuration) but it's probably because you're trying to use `awesome-typescript-loader` or `ts-loader` for this and in Angular they [use](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts#L23) a custom loader from `@ngtools/webpack`.

**Comment by Brandejs** [comment]
Sure [ng2-nameof-test](https://github.com/Brandejs/ng2-nameof-test). Its just simple new ng app and I'm trying to write to console in app.component.ts nameof that component.

**Comment by meltedspark** [comment]
Please try using the solution suggested [here](https://github.com/meltedspark/angular-builders/issues/179). Update me whether it works for your or not.

**Comment by Brandejs** [comment]
Hi, 

many thanks. `mergeStrategies: { "module": "prepend" }` solved the issue for me.

**Comment by asvishnyakov** [comment]
Not solve actually, because it just leave nameof() as is

**Comment by meltedspark** [comment]
Could you elaborate please?

**Comment by asvishnyakov** [comment]
With `mergeStrategies: { "module": "prepend" }` I receive `nameof()` operator as-is in compiled js files, so at runtime my app fails
