### ISSUE TITLE
Modify rule regex

### ISSUE THREAD

**Issue by mistic100** [meltedspark/angular-builders#257]
I need to change the loader used for SVG files.

Currently Angular CLI declares a rule on `\.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)$` and uses the file-loader.

**Is there a solution to alter the Regex of a an existing rule with angular-builders ?**

Previously I used ngx-build-plus and was able to alter the merge configuration with the "plugin" feature.
The plugin look likes :

```js
exports.default = {
    config: (cfg) => {
        const rules = cfg.module.rules;

        // Remove SVG from file-loader
        const fileLoader = rules.find(rule => {
            return rule.loader === 'file-loader';
        });

        if (!fileLoader) {
            throw 'Cannot find assets rule';
        }

        fileLoader.test = new RegExp(fileLoader.test.source.replace('|svg', ''), fileLoader.test.flags);

        // Add SVG to raw-loader
        rules.push({
            test  : /\.svg$/,
            loader: 'raw-loader',
        });

        return cfg;
    }
};
```

If this is not currently possible with angular-builders would you accept a Pull request to add such feature ?

**Comment by meltedspark** [comment]
I'm pretty sure it is not possible now without replacing the whole `rules` array.  
Allowing custom modifications is certainly a must have feature, and I think there is already a [pull request](https://github.com/meltedspark/angular-builders/pull/152) that does something very similar.  
The only difference is that it takes build options as a parameter instead of getting webpack config.  
Making it accept both as parameters `(cfg, buildOptions)` would be the right way to go in my opinion.  

This pull request, however, lacks UT tests, E2E tests and documentation.
I'd appreciate any contribution, but it would be really great if you contributed to this pull request instead of creating a new one. What do you think?

**Comment by mistic100** [comment]
Ok I can start form this PR, but it will be a new one anyway, I can't wait to know if jloscos allows me to access his repo.

**Comment by meltedspark** [comment]
Huh that's right, I'm just used to having access to all the PRs 😁.
Anyway, you got my point, I think that is a common functionality which should be implemented as one piece.

**Comment by mistic100** [comment]
Actually #152 is only about allowing the custom webpack file to export a function.

If I want to be able to alter the final configuration, I need a second file which will be called after "webpack-merge"

**Comment by mistic100** [comment]
What do you think about a single file with this structure ?

```js
module.exports = function(buildOptions) {
   return "extra configuration";
};

module.exports.postMerge = function(config) {
  return "full modified configuration";
};
```

**Comment by meltedspark** [comment]
Correct. I think that it should be as simple as possible. Meaning if the file exports an object then we merge it with default config. If the file exports a function then we pass the default config into this function and expect to get the final configuration in return.
Another way is supporting these options independently but I can't think why one would want to keep part of config as an object and apply another part in a function. Am I missing something?

**Comment by mistic100** [comment]
Ok so if it is a function there is no automatic merge at all, that's good to me.
