### ISSUE TITLE
Extra loaders don't seem to be working, do I have the correct syntax ?

### ISSUE THREAD

**Issue by appsolutegeek** [meltedspark/angular-builders#33]
Hi,

I have attempted to add a loader using the following changes, but the loader doesn't seem to be working as it complains about not being able to import graphql file

For sure, I have missed something but i can't figure out what it is. Are my syntaxes correct below including my extra webconfig config file ?

```
error TS2307: Cannot find module '@app/core/graphql/exchange.query.graphql'
```

here is my change to angular.json

```
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./extra-webpack.config.js"
            },
```

and

```
 "serve": {
          "builder": "@angular-builders/dev-server:generic",
          "options": {
            "browserTarget": "treasury-ui:build"
          },
```

and finally my extra-webpack.config.js (I know its at least loading the file as I placed a console.log() there, but the loaders dont seem to be appended..

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.(graphql|gql)$/,
        use: [
          {
            loader: 'webpack-graphql-loader'
          }
        ]
      }
    ]
  }
}

```

Thanks in advance for any information to help me figure out why the loaders are not being added.

**Comment by meltedspark** [comment]
Hi, would you mind trying a beta version `2.3.0-beta.1` and let me know if it works for you?

**Comment by meltedspark** [comment]
The configuration looks OK, and adding an extra loader should work (just like it works [here](https://github.com/meltedspark/electron-angular-native)).  
The error you mentioned points to a missing module, meaning webpack is not able to **find** the module rather than failing to load it.  
If the webpack wasn't able to load the module you would have gotten this error:
> "Module parse failed: Unexpected character ... You may need an appropriate loader to handle this file type."

On the other hand if the module is supported but not exists you get the error you described.  

So my guess would be that there is an issue with your tsconfig paths mapping or something like that.  
Have you tried specifying absolute path to the module?
