### ISSUE TITLE
using Ivy without Angular CLI

### ISSUE THREAD

**Issue by stepet80** [meltedspark/angular-builders#351]
I was pointed to this forum through following stackoverflow post:
https://stackoverflow.com/a/56748748/2174621

Is it possible to use Angular Ivy without Angular CLI. 
We have a plain webpack Angular application and we would like to use Ivy.

**Comment by meltedspark** [comment]
I'm sure it is possible but you'll have to dig in Angular CLI code and see where exactly they use `enableIvy` flag.   
I haven't seen your Webpack config but I guess you're using `AngularCompilerPlugin`. If yes then you have to provide it with option `enableIvy` in `compilerOptions`. For more details look [here](https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts).  
I'm not sure if they are using this flag in other places but in any case, if you want to save yourself a headache I'd recommend you to stick with Angular CLI.  Otherwise you'll have to visit their code base quite often.   
I don't think your setup is unique and basically anything that is done with pure Webpack can be also done with `custom-webpack` builder. I can help you with that.

**Comment by meltedspark** [comment]
The question was answered on SW.
