### ISSUE TITLE
Is it possible to access the config object?

### ISSUE THREAD

**Issue by hoefling** [meltedspark/angular-builders#67]
First of all, thank you so much for this great package, especially since there's no possibility to do `ng eject` in the latest angular-cli. Looking at the example project, I see an example of adding a custom plugin to the plugins list, so _adding_ new stuff isn't a problem. But is there an option to edit the current config? For example, I need to find the instance of `HtmlWebpackPlugin` in the current plugins list and add a chunk to `excludeChunks` list. I must admit I'm pretty new to the whole building ecosystem, so apologies if the question has an obvious answer.

**Comment by meltedspark** [comment]
Yes, this is totally possible. Since [plugins merge](https://github.com/meltedspark/angular-builders/issues/30) feature you can add an existing plugin (for example `HtmlWebpackPlugin`) with the delta you want to change (like additional entry in `excludeChunks` list) to your custom weboack config, and the builder will merge it with the existing instance provided by Angular. 
Keep in mind though that if there are default values in the plugin's constructor, they would override the corresponding values in the existing instance. So these you have to set explicitly to the same values Angular sets. But again, it is only in case the plugin set's default values to some fields.  
You can check out an example for plugins merge in the [unit tests](https://github.com/meltedspark/angular-builders/blob/master/packages/custom-webpack/src/webpack-config-merger.spec.ts).

**Comment by hoefling** [comment]
Hi, first of all - this works just as you described, many thanks! However, it gets even better - while searching for usage examples of `replaceDuplicatePlugins` in the issues, I found #13 which is exactly what I am trying to accomplish (bootstrapping the app in a web worker), with a working configuration. Copy & pasted, adapted script names and it just works. I'd propose this issue closed as I've found more than I was looking for. Again, thank you so much for this hidden gem and keep up the great work!
