### ISSUE TITLE
Unable to get options.configPath working

### ISSUE THREAD

**Issue by esotrope** [meltedspark/angular-builders#84]
Is it possible to add a warning log when the custom config path does not exist?
I am unable to troubleshoot why the jest angular builder cannot find my custom jest config.

The current `custom-config.resolver.ts`
```typescript
static resolveForProject(projectRoot: Path, configPath: string){
  const jestConfigPath = getSystemPath(join(projectRoot, configPath));  
  return existsSync(jestConfigPath) && require(jestConfigPath) || {};
}
```

I propose adding:
```typescript
console.log(`warning: unable to locate custom jest configuration at path "${jestConfigPath}"`);
```

The final code might look like:
```
static resolveForProject(projectRoot: Path, configPath: string){
  const jestConfigPath = getSystemPath(join(projectRoot, configPath));
  const exists = existsSync(jestConfigPath);
  if (!exists) {
    console.log(`warning: unable to locate custom jest configuration file at path "${jestConfigPath}"`);
    return {};
  }
  return require(jestConfigPath);
}
```
I would be more than happy to submit the PR myself if the concept is well received.
Thanks!

**Comment by meltedspark** [comment]
Sounds like a reasonable requirement to me.  
The implementation though shall be a bit different. You should use BuilderContext logger (like in [this](https://gist.github.com/meltedspark/b206fea21f78a30e8f6c44a6b989de21#file-timestamp-builder-ts) gist) instead of `console.log`.  
If you feel like implementing it - sure, go ahead! 

Also, as far as I understand, there are two problems here:
1. Absence of warning
2. Your specific problem with `jest.config` path

Did you manage to solve 2 or you need help with that?

**Comment by esotrope** [comment]
Thank you for the quick feedback!
I'll see if i can get something up for review this week.

As for the `jest.config.js` path - I am still not able to resolve this.
Currently, I have it working but only because I place the config at the default path (project root)

Below is a snippet of my file tree:
```bash
├── projects
│   ├── project1
│   └── project2
│       └── src
│           └── project2-jest.config.js
├── tools
│   └── jest
│       ├── jest-global-mocks.ts
│       └── setup-jest.ts
├── jest.config.js
└── angular.json
```

Here is the angular.json snippet:
```json
{
  "projects": {
    "project1": {
      "targets": {
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "preset": "jest-preset-angular",
            "setupTestFrameworkScriptFile": "<rootDir>/tools/jest/setup-jest.ts",
            "configPath": "<rootDir>/project1/src/project1-jest.config.js"
          }
        },
      }
    }
  }
}
```

For the config path I have also tried `./projects/project1/src/project1-jest.config.js` but this silently fails as well.

**Comment by esotrope** [comment]
Cool thanks! I figured it out after fiddling with the source code actually xD
Please checkout the PR: https://github.com/meltedspark/angular-builders/pull/87

**Comment by denis-itskovich** [comment]
Why does this warning make sense? What if I don't need custom config and the default one works fine? What if I configure custom configuration in `package.json` and not in `jest.config.js`?

**Comment by meltedspark** [comment]
Yeah, probably it should be displayed only in certain circumstances. The question is in which circumstances.  
Indeed, if you don't need custom config you're fine. But if you do need it and you place it in a different place... You probably want to see this warning.  
The builder hides complexity behind Jest setup. Part of it is that the user doesn't have to specify config path explicitly - he can just use the default path and put the custom config under the directory specified in the docs. The builder, however, cannot distinguish between config path that was specified explicitly and the default one since the default comes from the JSON schema which is parsed by architect.  
I'm open for suggestions though.
