### ISSUE TITLE
Help using Custom Webpack

### ISSUE THREAD

**Issue by frankiej45nz** [meltedspark/angular-builders#95]
I'm just looking for some guidance on using the custom webpack builder for server. I used ng eject previously to customize the webpack build to deal with the "SyntaxError: Unexpected token import" that occurs with some libraries (e.g. ngx-boostrap) for SSR. I'd like to achieve a way round this error using the custom webpack builder, but wondered if it can be done without doing a full replace? Any guidance would be appreciated 👍

**Comment by meltedspark** [comment]
Sure. The whole purpose of this project is to avoid unnecessary configuration duplication. You create a webpack config that only contains the *changes* you need to make to the original configuration, make changes in `angular.json` to apply `custom-webpack` builders and this is it.  
All this is described in the [docs](https://github.com/meltedspark/angular-builders/blob/master/README.md).  
If it's not clear enough or you having some issues with the configuration feel free to ask questions here. 
I'll close this one because it is not an issue, but I'll be glad to help you if you face any troubles.
